name: ask-db-nlq-cpu
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- pytorch
- torchvision
- cython
- spacy
- pip
- graphene
- path.py
- regex==2017.4.5
- babel
#For Stanford stanza - start
#  - requests  #covered
#  - ConfigArgParse==0.10.0 # requires python 2.7
- ConfigArgParse
- nose
- mock
- protobuf
- gunicorn
- pip:  
  - stanza
  - pypng
  - pyhocon
  - python-Levenshtein
  - google  
  #For Stanford stanza - end
  - torchtext
  - Flask-GraphQL
prefix: /home/stevop/.conda/envs/ask-db-nlq-cpu

